spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:slot_booking}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

telegram:
  bot:
    enabled: ${TELEGRAM_BOT_ENABLED:true}
    token: ${TELEGRAM_BOT_TOKEN}
